### ISSUE TITLE
AbstractMQEventListener启动时候可能会报空指针

### ISSUE THREAD

**Issue by cjiewong** [HangZhouShuChengKeJi/eventframework#8]
@Override
    public void onApplicationEvent(ApplicationEvent event) {
        if (event instanceof ContextRefreshedEvent) {
            if (!this.disableEventInfoReport) {
                this.eventFramework.uploadConsumerDisplayName(this);
            }
        }
    }
启动时候如果监听到了ContextRefreshedEvent事件，此时eventFramework尚未初始化，会报空指针异常。建议bean构建的时候直接初始化    private EventFramework eventFramework = EventFramework.getInstance();;

**Comment by yyhan** [comment]
已解决，参考： a69f5ba70c7a184f5a6329307e75b24eced106e9
